services:
  lumo-api:
    ports: !reset []
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true
    name: ${LUMO_PROXY_NETWORK:?Define LUMO_PROXY_NETWORK with the reverse proxy network}
